export const dogData = [
  { label: '래브라도 리트리버', value: '래브라도 리트리버' },
  { label: '골든 리트리버', value: '골든 리트리버' },
  { label: '보더 콜리', value: '보더 콜리' },
  { label: '저먼 셰퍼드', value: '저먼 셰퍼드' },
  { label: '오스트레일리언 셰퍼드', value: '오스트레일리언 셰퍼드' },
  { label: '잭 러셀 테리어', value: '잭 러셀 테리어' },
  { label: '비글', value: '비글' },
  { label: '코커 스패니얼', value: '코커 스패니얼' },
  { label: '치와와', value: '치와와' },
  { label: '시추', value: '시추' },
  { label: '요크셔 테리어', value: '요크셔 테리어' },
  { label: '퍼그', value: '퍼그' },
  { label: '슈나우저', value: '슈나우저' },
  { label: '시베리안 허스키', value: '시베리안 허스키' },
  { label: '오스트레일리안 캐틀독', value: '오스트레일리안 캐틀독' },
  { label: '복서', value: '복서' },
  { label: '닥스훈트', value: '닥스훈트' },
  { label: '카발리에 킹 찰스 스패니얼', value: '카발리에 킹 찰스 스패니얼' },
  { label: '말티즈', value: '말티즈' },
  { label: '스탠다드 푸들', value: '스탠다드 푸들' },
  { label: '보스턴 테리어', value: '보스턴 테리어' },
  { label: '포메라니안', value: '포메라니안' },
  { label: '미니어처 푸들', value: '미니어처 푸들' },
  { label: '잉글리시 스프링어 스패니얼', value: '잉글리시 스프링어 스패니얼' },
  { label: '토이 푸들', value: '토이 푸들' },
  { label: '웨스트 하일랜드 화이트 테리어', value: '웨스트 하일랜드 화이트 테리어' },
  { label: '로트바일러', value: '로트바일러' },
  { label: '스타포드셔 불 테리어', value: '스타포드셔 불 테리어' },
  { label: '아키타견', value: '아키타견' },
  { label: '버니즈 마운틴 도그', value: '버니즈 마운틴 도그' },
  { label: '웰시 코기', value: '웰시 코기' },
  { label: '시바견', value: '시바견' },
  { label: '빠삐용', value: '빠삐용' },
  { label: '프렌치 불도그', value: '프렌치 불도그' },
  { label: '진돗개', value: '진돗개' },
  { label: '풍산개', value: '풍산개' },
  { label: '삽살개', value: '삽살개' },
];

export const catData = [
  { label: '페르시안', value: '페르시안' },
  { label: '스코티쉬 폴드', value: '스코티쉬 폴드' },
  { label: '러시안 블루', value: '러시안 블루' },
]