require Pod::Executable.execute_command('node', ['-p',
'require.resolve(
"react-native/scripts/react_native_pods.rb",
{paths: [process.argv[1]]},
)', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# linkage = ENV['USE_FRAMEWORKS']
linkage = 'static'
if linkage != nil
Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
use_frameworks! :linkage => linkage.to_sym
end

target 'reactCapsone' do
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  config = use_native_modules!

  # React Native 기본 설정
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => false, # Hermes 비활성화
    :fabric_enabled => true  # Fabric 활성화
  )

  # post_install 단계 설정
  post_install do |installer|
    react_native_post_install(installer, :ccache_enabled => true)

    # # Apple Silicon 시뮬레이터 문제 방지 설정
    # installer.pods_project.build_configurations.each do |config|
    #   config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    # end
  end
end
