# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactCapsone' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  inherit! :complete
  # Pods for reactCapsone
  target 'reactCapsoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
